senera/cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('remove/<slug:product_id>/<slug:type>/', views.remove_from_cart, name="CartRemove"),
    path('add/<slug:product_id>/<slug:type>/', views.add_to_cart, name="CartAdd"),
    path('', views.CartOrder.as_view(), name="Cart"),
]

senera/senera/urls.py
from django.contrib import admin
from django.urls import path, include

from product import urls as product_urls
from cart import urls as cart_urls
from user import urls as user_urls
from order import urls as order_urls
from product.views import ViewMainPage

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings

app_name = 'senera'

urlpatterns = [
    path('', ViewMainPage.as_view(), name="MainPage"),
    path('admin/', admin.site.urls),
    path('bouqets/', include(product_urls)),
    path('cart/', include(cart_urls)),
    path('user/', include(user_urls)),
    path('order/', include(order_urls)),
    path('account/', include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

senera/templates/pages/main.html
{% extends 'base/base.html' %}
{% load raw_html %}

{% load static %}
{% block links %}
    <link href="{% static 'css/main_page.css' %}" rel='stylesheet' type='text/css'>
{% endblock %}

{% block content %}

    <header>
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <!-- Slide One - Set the background image for this slide in the line below -->
                <div class="carousel-item active" style="background-image: url('https://images.pexels.com/photos/949582/pexels-photo-949582.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940')">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>First Slide</h3>
                        <p>This is a description for the first slide.</p>
                    </div>
                </div>
                <!-- Slide Two - Set the background image for this slide in the line below -->
                <div class="carousel-item" style="background-image: url('https://images.pexels.com/photos/207172/pexels-photo-207172.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940')">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>Second Slide</h3>
                        <p>This is a description for the second slide.</p>
                    </div>
                </div>
                <!-- Slide Three - Set the background image for this slide in the line below -->
                <div class="carousel-item" style="background-image: url('https://images.pexels.com/photos/5971/hands-people-woman-flowers.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940')">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>Third Slide</h3>
                        <p>This is a description for the third slide.</p>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </header>

    <div class="row circles">
        <div class="col-lg-4 col-sm-4 col-xs-12 text-center">
          <img class="rounded-circle img-fluid d-block mx-auto" src="http://placehold.it/200x200" alt="">
          <!--<h3>Скорость</h3>-->
          <!--<p>Здесь преимущества компании</p>-->
        </div>
        <div class="col-lg-4 col-sm-4 col-xs-6 text-center">
          <img class="rounded-circle img-fluid d-block mx-auto" src="http://placehold.it/200x200" alt="">
        </div>
        <div class="col-lg-4 col-sm-4 col-xs-6 text-center">
          <img class="rounded-circle img-fluid d-block mx-auto" src="http://placehold.it/200x200" alt="">
        </div>
    </div>

    <h1 class="page-header">Популярные категории</h1>

    <div class="container top_category">
        <div class="row">
            <div id="top_1" class="col-md-6 col-sm-6 col-xs-12 top_block_category">
                <div class="category-item">
                    <a href="/">
                        <img src="https://images.pexels.com/photos/733883/pexels-photo-733883.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="yoga free demo collection 1" class="img-responsive">
                    </a>
                    <div class="category-item-description">
                        <h4><a href="/">Букеты из роз</a></h4>
                    </div>
                </div>
            </div>
            <div id="top_2" class="col-sm-6 col-md-6 col-xs-12 top_block_category">
                <div class="category-item">
                    <a href="/">
                        <img src="https://images.pexels.com/photos/122734/pexels-photo-122734.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="yoga free demo collection 1" class="img-responsive">
                    </a>
                    <div class="category-item-description">
                        <h4><a href="/">Ко дню всех влюбленных</a></h4>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div id="middle_1" class="col-md-4 col-sm-4 col-xs-12 top_block_category">
                <div class="category-item">
                    <a href="/">
                        <img src="https://images.pexels.com/photos/265815/pexels-photo-265815.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="yoga free demo collection 1" class="img-responsive">
                    </a>
                    <div class="category-item-description">
                        <h4><a href="/">С Днем Рождения</a></h4>
                    </div>
                </div>
            </div>
            <div id="middle_2" class="col-md-4 col-sm-4 col-xs-12 top_block_category"><div class="category-item">
                    <a href="/">
                        <img src="https://images.pexels.com/photos/343232/pexels-photo-343232.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="yoga free demo collection 1" class="img-responsive">
                    </a>
                    <div class="category-item-description">
                        <h4><a href="/">Букет из пионов</a></h4>
                    </div>
                </div></div>
            <div id="middle_3" class="col-md-4 col-sm-4 col-xs-12 top_block_category"><div class="category-item">
                    <a href="/">
                        <img src="https://images.pexels.com/photos/289519/pexels-photo-289519.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="yoga free demo collection 1" class="img-responsive">
                    </a>
                    <div class="category-item-description">
                        <h4><a href="/">На все случаи</a></h4>
                    </div>
                </div></div>
        </div>
    </div>

    <div class="container main_about">
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 main_text_about">
                <h2>SeneraFlowers</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut deleniti expedita, facilis fugit in
                    nostrum quos sed! Aliquam atque aut deleniti dignissimos earum maiores provident, quisquam saepe
                    similique soluta, voluptatibus!</p>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 main_image_about">
                <img src="https://upload.wikimedia.org/wikipedia/commons/3/3b/Logo-GoogleFonts-color-background.png"
                     alt="Image" class="img-responsive">
            </div>
        </div>
    </div>

{% endblock %}

senera/templates/pages/page_filter_by_tag.html
{% extends 'base/base.html' %}
{% load raw_html %}

{% load static %}
{% block links %}
    <link href="{% static 'css/page_tags.css' %}" rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
          integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
{% endblock %}

{% block content %}
    <div class="container page_tag_container">
        <div class="row">
            <div class="col-lg-3 col-md-3 col-xs-12 col-sm-12 page_tag_filter">
                <h3 class="d-none d-lg-block d-md-block">Filter</h3>
                    <ul>
                        <li class="d-sm-inline-block"><a href="/all/">Все букеты</a></li>
                        {% for tag in tags %}
                            <li><a href="{{ tag.get_absolute_url}}">{{ tag.name }}</a></li>
                        {% endfor %}
                    </ul>
            </div>
            <div class="col-lg-9 col-md-9 col-xs-12 col-sm-12 page_tag__products">
                <div class="row">
                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 page_tag_product">
                            <div class="cart_product">
                                {% with product.photos.all|first as act %}
                                    {% if act %}
                                        <a href="{{ product.get_absolute_url }}"><img src="{{ act.photo.url }}"
                                                                                      alt="{{ act.alt }}" style="width: 100%;">
                                        </a>
                                    {% endif %}
                                {% endwith %}
                                <div class="row">
                                    <div class="col-8">
                                        <h2 class="cart-title">
                                            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                        </h2>
                                        {% for option in product.options.options %}
                                            {% with option.values|first as first_price %}
                                                <p class="page_tag_price">
                                                    <i class="fas">От {{ first_price.price_corrector }}</i>
                                                    <i class="fas fa-ruble-sign fa-0.5x"></i>
                                                </p>
                                            {% endwith %}
                                        {% endfor %}
                                    </div>
                                    <div class="col-4 page_sale">
                                        {% with product.sale_product.all|first as first %}
                                            {% if first %}
                                            <i class="fas">-{{ first.value }}</i> <i class="fas {{ first.choice.value }}"></i>
                                            {% endif %}
                                        {% endwith %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

senera/templates/pages/page_product.html
{% extends 'base/base.html' %}
{% load raw_html %}

{% load static %}
{% block links %}
    <link href="{% static 'css/page_product.css' %}" rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
          integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
{% endblock %}

{% block content %}
    <div class="container product">
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <h2>{{ product.name }}</h2>
                <div class="links">
                    {% for tag in product.tags.all %}
                        <div class="link"><a href="{{ tag.get_absolute_url }}">{{ tag }}</a>&nbsp;</div>
                    {% endfor %}
                </div>
                <div class="product_image">
                    {% for product_photo in product.photos.all %}
                        {{ product_photo.image_tag|safe }}
                    {% endfor %}
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <h2>Описание</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium aut culpa cum, debitis distinctio dolor eius illo iste magnam minus neque perferendis quas quasi qui quidem repudiandae tempora voluptas voluptatum!</p>
                {% for option in product.options.options %}
                    {% for value in option.values %}
                        <div class="row product_price">
                            <form class="form-group" action="{% url "cart:CartAdd" product.id value.value %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">{{ value.value }}</button>
                            </form>
                            <h6><i class="fas">{{ value.price_corrector }}</i> <i class="fas fa-ruble-sign"></i></h6>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% with product.sale_product.all|first as first %}
                    {% if first %}
                    При заказе этого букета вы получите скидку <i class="fas">{{ first.value }}</i> <i class="fas {{ first.choice.value }}"></i>
                    {% endif %}
                {% endwith %}
            </div>
        </div>
    </div>
{% endblock %}