senera/cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('remove/<slug:product_id>/<slug:type>/', views.remove_from_cart, name="CartRemove"),
    path('add/<slug:product_id>/<slug:type>/', views.add_to_cart, name="CartAdd"),
    path('', views.CartOrder.as_view(), name="Cart"),
]

senera/order/urls.py
from django.urls import path
from order import views
from django.contrib.admin.views.decorators import staff_member_required

app_name = 'order'

urlpatterns = [
    path('', views.CartOrder.as_view(), name="Order"),
    path('pdf/<slug:order_id>/', staff_member_required(views.OrderPdf.as_view()), name="OrderPdf"),
    path('payment/', views.Payment.as_view(), name="Payment")
]

senera/senera/urls.py
from django.contrib import admin
from django.urls import path, include

from product import urls as product_urls
from cart import urls as cart_urls
from user import urls as user_urls
from order import urls as order_urls
from product.views import ViewMainPage

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings

app_name = 'senera'

urlpatterns = [
    path('', ViewMainPage.as_view(), name="MainPage"),
    path('admin/', admin.site.urls),
    path('bouqets/', include(product_urls)),
    path('cart/', include(cart_urls)),
    path('user/', include(user_urls)),
    path('order/', include(order_urls)),
    path('account/', include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

senera/cart/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType

# Модель корзины
class Cart(models.Model):
    creation_date = models.DateTimeField(verbose_name='Дата создания')
    checked_out = models.BooleanField(default=False, verbose_name='Проверка')

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'
        ordering = ['-creation_date']

class ItemManager(models.Manager):
    def get(self, *args, **kwargs):
        if 'product' in kwargs:
            kwargs['content_type'] = ContentType.objects.get_for_model(type(kwargs['product']))
            kwargs['object_id'] = kwargs['product'].pk
            del(kwargs['product'])
        return super(ItemManager, self).get(*args, **kwargs)

# Модель предметов корзины
class Item(models.Model):
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(verbose_name='Количество')
    price = models.PositiveIntegerField(verbose_name='Цена')
    type = models.CharField(max_length=200, verbose_name="Тип")
    # product as generic relation
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()

    objects = ItemManager()

    class Meta:
        verbose_name = 'Предмет'
        verbose_name_plural = 'Предметы'
        ordering = ['cart']

    def total_price(self):
        return self.quantity * self.price
    total_price = property(total_price)

    # product
    def get_product(self):
        return self.content_type.get_object_for_this_type(pk=self.object_id)

    def set_product(self, product):
        self.content_type = ContentType.objects.get_for_model(type(product))
        self.object_id = product.pk

    product = property(get_product, set_product)

senera/order/models.py
from django.db import models
from django.core.validators import RegexValidator
from product.models import Product

class OrderModel(models.Model):
    phone_regex = RegexValidator(regex=r'^\+?1?\d{10}$', message="Номер должен быть в формате '9633609225'")
    first_name = models.CharField(max_length=100, verbose_name='Имя получателя')
    last_name = models.CharField(max_length=100, blank=True, null=True, verbose_name='Фамилия получателя')
    number_phone = models.CharField(validators=[phone_regex], max_length=10, verbose_name='Номер телефона получателя')
    region = models.CharField(max_length=100, blank=True, null=True, verbose_name='Регион')
    city = models.CharField(max_length=100, verbose_name='Город')
    street = models.CharField(max_length=100, verbose_name='Улица')
    house_number = models.PositiveIntegerField(blank=True, null=True, verbose_name='Дом')
    housing_number = models.PositiveIntegerField(blank=True, null=True, verbose_name='Корпус')
    apartament_number = models.PositiveIntegerField(blank=True, null=True, verbose_name='Квартира')
    first_name_sender = models.CharField(max_length=100, verbose_name='Имя отправителя')
    email_sender = models.EmailField(verbose_name='Email отправителя')
    phone_sender = models.CharField(validators=[phone_regex], max_length=10, verbose_name='Телефон отправителя')
    status = models.BooleanField(default=False, verbose_name='Статус заказа')

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

class OrderItem(models.Model):
    order = models.ForeignKey(OrderModel, related_name='items', on_delete=models.CASCADE)
    product_name = models.CharField(max_length=200, verbose_name='Товар')
    quantity = models.PositiveIntegerField(verbose_name='Количество')
    type = models.CharField(max_length=200, verbose_name='Тип')
    total_price = models.PositiveIntegerField(verbose_name='Общая цена')

    def __str__(self):
        return 'Продукт'

    class Meta:
        verbose_name = 'Предмет заказа'
        verbose_name_plural = 'Предметы заказов'

senera/order/forms.py
from django import forms
from order.models import OrderModel

class OrderForm(forms.ModelForm):

    class Meta:
        model = OrderModel
        fields = ['first_name', 'last_name', 'number_phone', 'region', 'city', 'street', 'house_number',
                  'housing_number', 'apartament_number', 'first_name_sender', 'email_sender', 'phone_sender']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control',
                                                'id': 'inputFirstName', 'placeholder': 'Имя получателя'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control',
                                                'id': 'inputLastName', 'placeholder': 'Фамилия'}),
            'number_phone': forms.TextInput(attrs={'class': 'form-control',
                                                'id': 'inputNumberPhone', 'placeholder': 'Номер телефона'}),
            'region': forms.TextInput(attrs={'class': 'form-control',
                                                'id': 'inputRegion', 'placeholder': 'Область'}),
            'city': forms.TextInput(attrs={'class': 'form-control',
                                                'id': 'inputCity', 'placeholder': 'Город'}),
            'street': forms.TextInput(attrs={'class': 'form-control',
                                                'id': 'inputStreet', 'placeholder': 'Улица'}),
            'house_number': forms.TextInput(attrs={'class': 'form-control',
                                                'id': 'inputHouseNumber', 'placeholder': 'Дом'}),
            'housing_number': forms.TextInput(attrs={'class': 'form-control',
                                                'id': 'inputHousingNumber', 'placeholder': 'Корпус'}),
            'apartament_number': forms.TextInput(attrs={'class': 'form-control',
                                                'id': 'inputApartamentNumber', 'placeholder': 'Квартира'}),
            'first_name_sender': forms.TextInput(attrs={'class': 'form-control',
                                                'id': 'inputFirstNameSender', 'placeholder': 'Имя'}),
            'email_sender': forms.TextInput(attrs={'class': 'form-control',
                                                'id': 'inputEmailSender', 'placeholder': 'email'}),
            'phone_sender': forms.TextInput(attrs={'class': 'form-control',
                                                'id': 'inputPhoneSender', 'placeholder': 'Номер телефона'})
        }

senera/cart/views.py
from product.models import Category, Product, Tags, ProductPhoto
from django.shortcuts import render_to_response, redirect, render
from .cart import Cart
from django.views.generic import FormView
from order.forms import OrderForm
from django.http import HttpResponseRedirect, HttpResponse
from order.models import OrderItem
from sale.sale import Sale


def add_to_cart(request, product_id, type):
    product = Product.objects.get(id=product_id)
    cart = Cart(request)
    price = cart.find_price(product, type)
    if product.sale_product.count():
        price = Sale().sale(product=product, price=price)

    cart.add(product, price=price, quantity=1, type=type)
    total_summ = cart.summary()
    return redirect('/cart', {'cart': Cart(request), 'total': total_summ})

def remove_from_cart(request, product_id, type):
    product = Product.objects.get(id=product_id)
    cart = Cart(request)
    cart.remove(product, type)
    return HttpResponseRedirect('/')

class CartOrder(FormView):
    template_name = 'cart/cart.html'
    form_class = OrderForm
    success_url = '/'

    def form_valid(self, form):
        form.save()
        return super(CartOrder, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CartOrder, self).get_context_data(**kwargs)
        context['cart'] = Cart(self.request)
        context['total_summ'] = Cart(self.request).summary()
        return context

senera/order/views.py
from order.forms import OrderForm
from order.models import OrderItem, OrderModel
from cart.cart import Cart

from django.views.generic.edit import FormView, View
from django.views.generic.base import TemplateView
from django.http import HttpResponseRedirect, HttpResponse
from django.template.loader import render_to_string
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User

import weasyprint


class CartOrder(FormView):
    template_name = 'cart/cart.html'
    form_class = OrderForm
    success_url = '/'

    # Этот запрос принимает заполненную форму, отправляет в БД и генерирует PDF
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        order = {}
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            cart = Cart(self.request)
            for i in cart:
                items = OrderItem.objects.create(order_id=post.id, product_name=i.product.name, quantity=i.quantity,
                                         type=i.type, total_price=i.total_price)
            return HttpResponseRedirect('/')
        else:
            return HttpResponse('Введите корректные данные!!!')


class OrderPdf(View):

    def get(self, request, order_id):
        order = get_object_or_404(OrderModel, id=order_id)
        result = 0
        for item in order.items.all():
            result += item.total_price
        html = render_to_string('cart/order.html', {'order': order, 'result': result})
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'filename=order_{}.pdf'.format(order.id)
        weasyprint.HTML(string=html).write_pdf(response,
                                               stylesheets=[
                                                   weasyprint.CSS('static/vendor/bootstrap/css/'
                                                                  'bootstrap.min.css')])
        return response

class Payment(TemplateView):
    template_name = 'cart/payment.html'

    def get_context_data(self):
        context = super(Payment, self).get_context_data()
        cart = Cart(self.request)
        result = 0
        for item in cart:
            result += item.total_price
        count = 0
        string = ''
        for i in cart:
            general = '&LMI_SHOPPINGCART.ITEMS[{}]'.format(count)
            string += general + '.NAME={}'.format(i.product.name)
            string += general + '.QTY={}'.format(i.quantity)
            string += general + '.PRICE={}'.format(i.price)
            string += general + '.TAX=vat0'
            count += 1
        context['string'] = string
        print(string)
        context['result'] = result
        return context

senera/templates/cart/cart.html
{% extends 'base/base.html' %}

{% load static %}
{% block links %}
    <link href="{% static 'css/cart.css' %}" rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/cart_validation_form.js' %}"></script>
{% endblock %}

{% block content %}

    <div class="container cart">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 row">
                {% for item in cart %}
                    <div class="col-sm-12 col-xs-12">
                        <div class="row">
                            <div class="col-6">
                                <h2>{{ item.product.name }}</h2>
                                <div class="product_image">
                                    {% with image=item.product.photos_thumbnail %}
                                        {{ image.image_tag|safe }}
                                    {% endwith %}
                                </div>
                            </div>
                            <div class="col-6 m-auto">
                                <ul class="p-0">
                                    <li><i class="fas fa-gift"></i> {{ item.quantity }}</li>
                                    <li><i class="fas fa-chart-pie"></i> {{ item.type }}</li>
                                    <li><i class="fas fa-ruble-sign"></i> {{ item.total_price }}</li>
                                    <li><i class="fas fa-trash"></i> <a href="{% url 'cart:CartRemove' item.product.id item.type %}">Удалить</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% empty %}

                    <h3>Начните покупку с <a href="/all">лучших букетов</a></h3>
                {% endfor %}
                <p>{{ cart.summary }}</p>,
            </div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <form  action="{% url 'order:Order' %}" method="post" class="needs-validation" novalidate>
                    {% csrf_token %}
                    <h3>Получатель</h3>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            {{ form.first_name }}
                        </div>
                        <div class="form-group col-md-4">
                            {{ form.last_name }}
                        </div>
                        <div class="form-group col-md-4">
                            {{ form.number_phone }}
                        </div>
                    </div>
                    <h3>Адрес доставки</h3>
                    <div class="form-row">
                        <div class="col-md-6 mb-3">
                            {{ form.region }}
                            <div class="invalid-feedback">
                                Введите регион доставки
                            </div>
                        </div>
                        <div class="col-md-6 mb-3">
                            {{ form.city }}
                            <div class="invalid-feedback">
                                Введите город доставки
                            </div>
                        </div>
                        <div class="col-md-4 mb-3">
                            {{ form.street }}
                            <div class="invalid-feedback">
                                Введите улицу
                            </div>
                        </div>
                        <div class="col-md-2 mb-3">
                            {{ form.house_number }}
                            <div class="invalid-feedback">
                                Введите номер дома
                            </div>
                        </div>
                        <div class="col-md-3 mb-3">
                            {{ form.housing_number }}
                        </div>
                        <div class="col-md-3 mb-3">
                            {{ form.apartament_number }}
                        </div>
                    </div>
                    <h3>Отправитель</h3>
                    <div class="form-row">
                        <div class="col-md-4 mb-3">
                            {{ form.first_name_sender }}
                            <div class="valid-feedback">
                                Looks good!
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            {{ form.email_sender }}
                        </div>
                        <div class="form-group col-md-4">
                            {{ form.phone_sender }}
                        </div>
                    </div>
                    <button class="btn btn-primary" type="submit">Submit form</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

senera/templates/cart/order.html
<html>
{% load pass %}

<body>
    <h1>Онлайн-магазин</h1>
    <p>
        Номер заказа: <b>{{ order.id }}</b>
        <br>
    </p>
    <div class="container">
        <div class="row">
            <div class="col-6 buyer">
                <h3>Покупатель</h3>
                <p>{{ order.first_name_sender }}
                    <br> {{ order.phone_sender }}
                    <br> {{ order.email_sender }}
                </p>
            </div>
            <div class="col-6 recipient">
                <h3>Получатель</h3>
                <p>{{ order.first_name }}&nbsp;{{ order.last_name|pass_value }}
                    <br>{{ order.number_phone }}
                    <br>{{ order.region|pass_value }} {{ order.city }} {{ order.street }}
                    {{ order.house_number|pass_value }} {{ order.housing_number|pass_value }} {{ order.apartament_number|pass_value }}
                </p>

            </div>
        </div>
        <h3>Купленные товары</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Товар</th>
                    <th>Стоймость</th>
                    <th>Количество</th>
                    <th>Общая сумма</th>
                </tr>
            </thead>
            <tbody>
                {% for item in order.items.all %}
                    <tr>
                        <td>{{ item.product_name }}</td>
                        <td>{{ item.type }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.total_price }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <h4>Всего: {{ result }}</h4>
    </div>
</body>

</html>

senera/templates/cart/payment.html
{% extends 'base/base.html' %}

{% block content %}

{% endblock %}

{% block scripts %}
    <script type='text/javascript' src='https://paymaster.ru/widget/Basic/1?LMI_MERCHANT_ID=
    42b11b46-58b8-487c-a2d5-4d56a3e1f6d1&LMI_PAYMENT_AMOUNT={{ result }}&LMI_PAYMENT_DESC=
    Платеж за заказ 50 в интернет-магазине Розарио&LMI_CURRENCY=RUB&LMI_PAYMENT_NO=
    {{ string }}'></script>
{% endblock %}